INSERT INTO public.teams (name, flag_code) VALUES ('Paises Baixos','nl'),('R. D. Congo','cd'),('Bosnia Herzegovina','ba'),('Republica Tcheca','cz'),('Curacau','cw') ON CONFLICT (name) DO NOTHING;
UPDATE public.matches SET home='Paises Baixos' WHERE home='Holanda';
UPDATE public.matches SET away='Paises Baixos' WHERE away='Holanda';
UPDATE public.matches SET home='R. D. Congo' WHERE home='Rep. Congo';
UPDATE public.matches SET away='R. D. Congo' WHERE away='Rep. Congo';
UPDATE public.matches SET home='Bosnia Herzegovina' WHERE home='Bosnia';
UPDATE public.matches SET away='Bosnia Herzegovina' WHERE away='Bosnia';
UPDATE public.matches SET home='Republica Tcheca' WHERE home='Tchequia';
UPDATE public.matches SET away='Republica Tcheca' WHERE away='Tchequia';
UPDATE public.matches SET home='Curacau' WHERE home='Curacao';
UPDATE public.matches SET away='Curacau' WHERE away='Curacao';
DELETE FROM public.teams WHERE name IN ('Holanda','Rep. Congo','Bosnia','Tchequia','Curacao');
UPDATE public.matches SET date='2026-06-14', time_brt='01:00' WHERE id=8;
UPDATE public.matches SET time_brt='21:30' WHERE id=31;
UPDATE public.matches SET time_brt='00:00' WHERE id=32;
UPDATE public.matches SET time_brt='18:00' WHERE id=42;
UPDATE public.matches SET time_brt='21:00' WHERE id=43;
UPDATE public.matches SET date='2026-06-23', time_brt='00:00' WHERE id=44;
UPDATE public.matches SET date='2026-06-23', time_brt='23:00' WHERE id=48;
UPDATE public.matches SET time_brt='19:00' WHERE id IN (51,52);
UPDATE public.matches SET date='2026-06-27', time_brt='00:00' WHERE id IN (65,66);